//! Integration tests for the resolv.conf takeover, run against a temporary
//! directory tree so the real system files are never touched.

use std::fs;
use std::net::IpAddr;

use dns_helper::resolvconf::{ResolvError, ResolvManager, TakeoverState};

struct Sandbox {
    _dir: tempfile::TempDir,
    resolv: std::path::PathBuf,
    state_dir: std::path::PathBuf,
    nm_dropin: std::path::PathBuf,
}

impl Sandbox {
    fn new(resolv_contents: &str) -> Self {
        let dir = tempfile::tempdir().expect("tempdir");
        let resolv = dir.path().join("resolv.conf");
        let state_dir = dir.path().join("state");
        let nm_dir = dir.path().join("NetworkManager/conf.d");
        fs::create_dir_all(&nm_dir).unwrap();
        fs::write(&resolv, resolv_contents).unwrap();
        Self {
            _dir: dir,
            resolv,
            state_dir,
            nm_dropin: nm_dir.join("00-detour.conf"),
        }
    }

    fn manager(&self) -> ResolvManager {
        ResolvManager::new(&self.resolv, &self.state_dir, &self.nm_dropin)
    }

    fn resolv_contents(&self) -> String {
        fs::read_to_string(&self.resolv).unwrap()
    }
}

fn proxy_ip() -> IpAddr {
    "127.0.0.53".parse().unwrap()
}

const ORIGINAL: &str = "# Generated by NetworkManager\nnameserver 8.8.8.8\nnameserver 8.8.4.4\n";

#[test]
fn takeover_rewrites_resolv_conf_and_records_originals() {
    let sandbox = Sandbox::new(ORIGINAL);
    let manager = sandbox.manager();

    let state = manager.take_over(proxy_ip()).expect("takeover succeeds");

    assert!(sandbox.resolv_contents().contains("nameserver 127.0.0.53"));
    assert_eq!(
        state.original_nameservers,
        vec![
            "8.8.8.8".parse::<IpAddr>().unwrap(),
            "8.8.4.4".parse::<IpAddr>().unwrap()
        ]
    );
    assert!(manager.is_active().unwrap());
}

#[test]
fn restore_returns_the_original_file_byte_for_byte() {
    let sandbox = Sandbox::new(ORIGINAL);
    let manager = sandbox.manager();

    manager.take_over(proxy_ip()).unwrap();
    assert_ne!(sandbox.resolv_contents(), ORIGINAL);

    manager.restore().unwrap();
    assert_eq!(
        sandbox.resolv_contents(),
        ORIGINAL,
        "restore must reproduce the original exactly"
    );
    assert!(!manager.is_active().unwrap());
}

#[test]
fn crash_recovery_restores_when_the_owning_process_is_gone() {
    let sandbox = Sandbox::new(ORIGINAL);
    let manager = sandbox.manager();
    manager.take_over(proxy_ip()).unwrap();

    // Simulate a crash: rewrite the state file to name a PID that cannot exist.
    let state_path = sandbox.state_dir.join("state.json");
    let mut state: TakeoverState =
        serde_json::from_str(&fs::read_to_string(&state_path).unwrap()).unwrap();
    state.pid = 0x7FFF_FFFE;
    fs::write(&state_path, serde_json::to_string(&state).unwrap()).unwrap();

    assert!(!manager.is_active().unwrap(), "dead pid must not read as active");

    let recovered = manager
        .reconcile_after_crash()
        .expect("reconcile succeeds")
        .expect("a crash was found");
    assert_eq!(recovered.pid, 0x7FFF_FFFE);
    assert_eq!(
        sandbox.resolv_contents(),
        ORIGINAL,
        "a crashed run must leave the system resolving normally"
    );
}

#[test]
fn reconcile_refuses_to_disturb_a_live_takeover() {
    let sandbox = Sandbox::new(ORIGINAL);
    let manager = sandbox.manager();
    manager.take_over(proxy_ip()).unwrap();

    // State names our own live PID, so this is not a crash.
    assert!(matches!(
        manager.reconcile_after_crash(),
        Err(ResolvError::AlreadyActive(_))
    ));
    assert!(sandbox.resolv_contents().contains("127.0.0.53"));
}

#[test]
fn second_takeover_while_active_is_refused() {
    let sandbox = Sandbox::new(ORIGINAL);
    let manager = sandbox.manager();
    manager.take_over(proxy_ip()).unwrap();

    assert!(matches!(
        manager.take_over(proxy_ip()),
        Err(ResolvError::AlreadyActive(_))
    ));
}

#[test]
fn reconcile_is_a_noop_when_nothing_was_taken_over() {
    let sandbox = Sandbox::new(ORIGINAL);
    let manager = sandbox.manager();
    assert!(manager.reconcile_after_crash().unwrap().is_none());
    assert_eq!(sandbox.resolv_contents(), ORIGINAL);
}

#[test]
fn restore_without_backup_reports_no_backup() {
    let sandbox = Sandbox::new(ORIGINAL);
    assert!(matches!(
        sandbox.manager().restore(),
        Err(ResolvError::NoBackup)
    ));
    assert_eq!(sandbox.resolv_contents(), ORIGINAL);
}

#[test]
fn restore_twice_is_safe() {
    let sandbox = Sandbox::new(ORIGINAL);
    let manager = sandbox.manager();
    manager.take_over(proxy_ip()).unwrap();
    manager.restore().unwrap();
    assert!(matches!(manager.restore(), Err(ResolvError::NoBackup)));
    assert_eq!(sandbox.resolv_contents(), ORIGINAL);
}

#[test]
fn networkmanager_dropin_is_written_and_removed() {
    let sandbox = Sandbox::new(ORIGINAL);
    let manager = sandbox.manager();

    manager.take_over(proxy_ip()).unwrap();
    let dropin = fs::read_to_string(&sandbox.nm_dropin).expect("drop-in written");
    assert!(dropin.contains("dns=none"));

    manager.restore().unwrap();
    assert!(!sandbox.nm_dropin.exists(), "drop-in must be cleaned up");
}

#[test]
fn preexisting_networkmanager_dropin_is_left_alone() {
    let sandbox = Sandbox::new(ORIGINAL);
    fs::write(&sandbox.nm_dropin, "# user's own file\n").unwrap();
    let manager = sandbox.manager();

    manager.take_over(proxy_ip()).unwrap();
    manager.restore().unwrap();

    assert_eq!(
        fs::read_to_string(&sandbox.nm_dropin).unwrap(),
        "# user's own file\n",
        "a file we did not create must never be deleted"
    );
}

#[test]
fn symlinked_resolv_conf_is_restored_as_a_symlink() {
    let dir = tempfile::tempdir().unwrap();
    let real = dir.path().join("real-resolv.conf");
    let link = dir.path().join("resolv.conf");
    fs::write(&real, ORIGINAL).unwrap();
    std::os::unix::fs::symlink(&real, &link).unwrap();

    let manager = ResolvManager::new(&link, dir.path().join("state"), dir.path().join("nm.conf"));
    manager.take_over(proxy_ip()).unwrap();
    manager.restore().unwrap();

    let meta = fs::symlink_metadata(&link).unwrap();
    assert!(
        meta.file_type().is_symlink(),
        "restore must put the symlink back, not a regular file"
    );
    assert_eq!(fs::read_link(&link).unwrap(), real);
}

#[test]
fn takeover_never_leaves_the_system_without_a_nameserver() {
    let sandbox = Sandbox::new(ORIGINAL);
    let manager = sandbox.manager();

    // At every observable point there must be a usable nameserver line.
    manager.take_over(proxy_ip()).unwrap();
    assert!(sandbox.resolv_contents().contains("nameserver "));

    manager.restore().unwrap();
    assert!(sandbox.resolv_contents().contains("nameserver "));
}

#[test]
fn empty_original_resolv_conf_is_handled() {
    let sandbox = Sandbox::new("");
    let manager = sandbox.manager();
    let state = manager.take_over(proxy_ip()).unwrap();
    assert!(state.original_nameservers.is_empty());
    manager.restore().unwrap();
    assert_eq!(sandbox.resolv_contents(), "");
}
